[[language]]
name = "haskell"
scope = "source.haskell"
injection-regex = "haskell"
file-types = ["hs", "hs-boot"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
comment-token = "--"
language-server = { command = "haskell-language-server-wrapper", args = ["--lsp"] }
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "haskell"
source = { git = "https://github.com/tree-sitter/tree-sitter-haskell", rev = "98fc7f59049aeb713ab9b72a8ff25dcaaef81087" }

#[language.config.haskell.inlayHints]
#includeInlayEnumMemberValueHints = true
#includeInlayFunctionLikeReturnTypeHints = true
#includeInlayFunctionParameterTypeHints = true
#includeInlayParameterNameHints = "all"                       # 'none' | 'literals' | 'all';
#includeInlayParameterNameHintsWhenArgumentMatchesName = true
#includeInlayPropertyDeclarationTypeHints = true
#includeInlayVariableTypeHints = true

[[language]]
name = "c-sharp"
scope = "source.cs"
injection-regex = "c-?sharp"
roots = ["sln", "csproj"]
file-types = ["cs"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
language-server = { command = "OmniSharp", args = ["-lsp"], timeout=10000 }

##[language.config.c-sharp.inlayHints]
##includeInlayEnumMemberValueHints = true
##includeInlayFunctionLikeReturnTypeHints = true
##includeInlayFunctionParameterTypeHints = true
##includeInlayParameterNameHints = "all"                       # 'none' | 'literals' | 'all';
##includeInlayParameterNameHintsWhenArgumentMatchesName = true
##includeInlayPropertyDeclarationTypeHints = true
##includeInlayVariableTypeHints = true
#[[c-sharp]]
#[language.config]
#inlayHintsOptions.enableForParameters = true
#inlayHintsOptions.forLiteralParameters = true
#inlayHintsOptions.forIndexerParameters = true
#inlayHintsOptions.forObjectCreationParameters = true
#inlayHintsOptions.forOtherParameters = true
#inlayHintsOptions.suppressForParametersThatDifferOnlyBySuffix = false
#inlayHintsOptions.suppressForParametersThatMatchMethodIntent = false
#inlayHintsOptions.suppressForParametersThatMatchArgumentName = false
#inlayHintsOptions.enableForTypes = true
#inlayHintsOptions.forImplicitVariableTypes = true
#inlayHintsOptions.forLambdaParameterTypes = true
#inlayHintsOptions.forImplicitObjectCreation = true

#"inlayHintsOptions": {
        #"enableForParameters": true,
        #"forLiteralParameters": true,
        #"forIndexerParameters": true,
        #"forObjectCreationParameters": true,
        #"forOtherParameters": true,
        #"suppressForParametersThatDifferOnlyBySuffix": false,
        #"suppressForParametersThatMatchMethodIntent": false,
        #"suppressForParametersThatMatchArgumentName": false,
        #"enableForTypes": true,
        #"forImplicitVariableTypes": true,
        #"forLambdaParameterTypes": true,
        #"forImplicitObjectCreation": true
    #}