import:
  - /home/vb/dotfiles/config/alacritty/themes/rose-pine-dawn.yaml

env:
  TERM: xterm-256color

font:
  size: 10.0
  family: JetBrains Mono
#shell:
  #program: /bin/bash
  #args:
    #- --login
#
key_bindings:
  - { key: F11, action: ToggleFullscreen }
