icons_format = "{icon}"

[theme]
theme = "srcery"
[theme.overrides]
idle_bg = "#21202e"
idle_fg = "#f2e9e1"

[icons]
icons = "material-nf"
#[icons.overrides]
#bat = ["|E|", "|_|", "|=|", "|F|"]
#bat_charging = "|^| "

[[block]]
block = "custom"
command = "xkblayout-state print \"%s\""
interval = 1

#[[block]]
#block = "net"
#format = "$icon {$signal_strength $ssid}"

#[[block]]
#block = "cpu"
#
#[[block]]
#block = "disk_space"
#path = "/"
#info_type = "available"
#alert_unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#format = " $icon MyPorn: $available.eng(w:2) "
#
#[[block]]
#block = "memory"
#format = " $icon $mem_total_used_percents.eng(w:2) "
#format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
device = "amdgpu_bl0"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "battery"
missing_format = ""
