# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];


  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices."luks-2f5a9126-62cd-4b6a-a2f8-6c5640873da3".device = "/dev/disk/by-uuid/2f5a9126-62cd-4b6a-a2f8-6c5640873da3";

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.extraModprobeConfig = ''
    options snd slots=snd-hda-intel
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fc06a51d-782a-4a5e-8d2f-103fac7f075c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6acfbf54-8ece-498b-b83b-2ad8d831fdbc".device = "/dev/disk/by-uuid/6acfbf54-8ece-498b-b83b-2ad8d831fdbc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0561-5E76";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d6752e25-f17c-4def-b243-b90532e85d65"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true;
}
